version: "3"

services:
    postgres:
        image: postgres:12.2-alpine
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - .env

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8081
